name: DEPLOY - DEV
on:
  workflow_dispatch:
jobs:
  terraform:
    name: deploy
    uses: GabrielSoares-Dev/workflows/.github/workflows/terraform-deploy.yml@master
    with:
      work_dir: ./
      environment: dev
      env_vars_path: env/dev.tfvars
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
